// Code generated by ent, DO NOT EDIT.

package orm

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	ormaddress "github.com/codemaestro64/filament/apps/api/internal/infra/database/orm/address"
	"github.com/codemaestro64/filament/apps/api/internal/infra/database/orm/wallet"
	"github.com/codemaestro64/filament/libs/filwallet/address"
)

// Address is the model entity for the Address schema.
type Address struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type address.Type `json:"type,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AddressQuery when eager-loading is set.
	Edges            AddressEdges `json:"edges"`
	wallet_addresses *int
	selectValues     sql.SelectValues
}

// AddressEdges holds the relations/edges for other nodes in the graph.
type AddressEdges struct {
	// Wallet holds the value of the wallet edge.
	Wallet *Wallet `json:"wallet,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WalletOrErr returns the Wallet value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AddressEdges) WalletOrErr() (*Wallet, error) {
	if e.Wallet != nil {
		return e.Wallet, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: wallet.Label}
	}
	return nil, &NotLoadedError{edge: "wallet"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Address) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ormaddress.FieldID, ormaddress.FieldType:
			values[i] = new(sql.NullInt64)
		case ormaddress.FieldAddress:
			values[i] = new(sql.NullString)
		case ormaddress.ForeignKeys[0]: // wallet_addresses
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Address fields.
func (_m *Address) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ormaddress.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ormaddress.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = address.Type(value.Int64)
			}
		case ormaddress.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case ormaddress.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field wallet_addresses", value)
			} else if value.Valid {
				_m.wallet_addresses = new(int)
				*_m.wallet_addresses = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Address.
// This includes values selected through modifiers, order, etc.
func (_m *Address) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWallet queries the "wallet" edge of the Address entity.
func (_m *Address) QueryWallet() *WalletQuery {
	return NewAddressClient(_m.config).QueryWallet(_m)
}

// Update returns a builder for updating this Address.
// Note that you need to call Address.Unwrap() before calling this method if this Address
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Address) Update() *AddressUpdateOne {
	return NewAddressClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Address entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Address) Unwrap() *Address {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("orm: Address is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Address) String() string {
	var builder strings.Builder
	builder.WriteString("Address(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteByte(')')
	return builder.String()
}

// Addresses is a parsable slice of Address.
type Addresses []*Address
