// Code generated by ent, DO NOT EDIT.

package orm

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	ormaddress "github.com/codemaestro64/filament/apps/api/internal/infra/database/orm/address"
	"github.com/codemaestro64/filament/apps/api/internal/infra/database/orm/predicate"
	"github.com/codemaestro64/filament/apps/api/internal/infra/database/orm/wallet"
	"github.com/codemaestro64/filament/libs/filwallet/address"
)

// AddressUpdate is the builder for updating Address entities.
type AddressUpdate struct {
	config
	hooks    []Hook
	mutation *AddressMutation
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdate) Where(ps ...predicate.Address) *AddressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *AddressUpdate) SetType(v address.Type) *AddressUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableType(v *address.Type) *AddressUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *AddressUpdate) AddType(v address.Type) *AddressUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetAddress sets the "address" field.
func (_u *AddressUpdate) SetAddress(v string) *AddressUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *AddressUpdate) SetNillableAddress(v *string) *AddressUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetWalletID sets the "wallet" edge to the Wallet entity by ID.
func (_u *AddressUpdate) SetWalletID(id int) *AddressUpdate {
	_u.mutation.SetWalletID(id)
	return _u
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (_u *AddressUpdate) SetWallet(v *Wallet) *AddressUpdate {
	return _u.SetWalletID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdate) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (_u *AddressUpdate) ClearWallet() *AddressUpdate {
	_u.mutation.ClearWallet()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AddressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AddressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdate) check() error {
	if v, ok := _u.mutation.Address(); ok {
		if err := ormaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`orm: validator failed for field "Address.address": %w`, err)}
		}
	}
	if _u.mutation.WalletCleared() && len(_u.mutation.WalletIDs()) > 0 {
		return errors.New(`orm: clearing a required unique edge "Address.wallet"`)
	}
	return nil
}

func (_u *AddressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ormaddress.Table, ormaddress.Columns, sqlgraph.NewFieldSpec(ormaddress.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(ormaddress.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(ormaddress.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(ormaddress.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ormaddress.WalletTable,
			Columns: []string{ormaddress.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ormaddress.WalletTable,
			Columns: []string{ormaddress.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ormaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AddressUpdateOne is the builder for updating a single Address entity.
type AddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AddressMutation
}

// SetType sets the "type" field.
func (_u *AddressUpdateOne) SetType(v address.Type) *AddressUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableType(v *address.Type) *AddressUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *AddressUpdateOne) AddType(v address.Type) *AddressUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetAddress sets the "address" field.
func (_u *AddressUpdateOne) SetAddress(v string) *AddressUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *AddressUpdateOne) SetNillableAddress(v *string) *AddressUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetWalletID sets the "wallet" edge to the Wallet entity by ID.
func (_u *AddressUpdateOne) SetWalletID(id int) *AddressUpdateOne {
	_u.mutation.SetWalletID(id)
	return _u
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (_u *AddressUpdateOne) SetWallet(v *Wallet) *AddressUpdateOne {
	return _u.SetWalletID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_u *AddressUpdateOne) Mutation() *AddressMutation {
	return _u.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (_u *AddressUpdateOne) ClearWallet() *AddressUpdateOne {
	_u.mutation.ClearWallet()
	return _u
}

// Where appends a list predicates to the AddressUpdate builder.
func (_u *AddressUpdateOne) Where(ps ...predicate.Address) *AddressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AddressUpdateOne) Select(field string, fields ...string) *AddressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Address entity.
func (_u *AddressUpdateOne) Save(ctx context.Context) (*Address, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AddressUpdateOne) SaveX(ctx context.Context) *Address {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AddressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AddressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AddressUpdateOne) check() error {
	if v, ok := _u.mutation.Address(); ok {
		if err := ormaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`orm: validator failed for field "Address.address": %w`, err)}
		}
	}
	if _u.mutation.WalletCleared() && len(_u.mutation.WalletIDs()) > 0 {
		return errors.New(`orm: clearing a required unique edge "Address.wallet"`)
	}
	return nil
}

func (_u *AddressUpdateOne) sqlSave(ctx context.Context) (_node *Address, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ormaddress.Table, ormaddress.Columns, sqlgraph.NewFieldSpec(ormaddress.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`orm: missing "Address.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ormaddress.FieldID)
		for _, f := range fields {
			if !ormaddress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("orm: invalid field %q for query", f)}
			}
			if f != ormaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(ormaddress.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(ormaddress.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(ormaddress.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ormaddress.WalletTable,
			Columns: []string{ormaddress.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ormaddress.WalletTable,
			Columns: []string{ormaddress.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Address{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ormaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
