// Code generated by gen-constants.go. DO NOT EDIT.
package app

const (
	WS_EVENT_PONG           = "pong"
	WS_EVENT_CONNECTED      = "connected"
	WS_EVENT_DISCONNECT     = "disconnect"
	WS_EVENT_WALLET_UPDATE  = "wallet:update"
	WS_EVENT_WALLETS_LOADED = "wallets:loaded"
	WS_EVENT_AUTH_REQUIRED  = "auth:required"
	WS_EVENT_PING           = "ping"
)
