// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pb/wallet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletsRequest) Reset() {
	*x = WalletsRequest{}
	mi := &file_pb_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletsRequest) ProtoMessage() {}

func (x *WalletsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletsRequest.ProtoReflect.Descriptor instead.
func (*WalletsRequest) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{0}
}

type WalletsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLocked      bool                   `protobuf:"varint,1,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	Wallets       []*WalletResponse      `protobuf:"bytes,2,rep,name=wallets,proto3" json:"wallets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletsResponse) Reset() {
	*x = WalletsResponse{}
	mi := &file_pb_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletsResponse) ProtoMessage() {}

func (x *WalletsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletsResponse.ProtoReflect.Descriptor instead.
func (*WalletsResponse) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *WalletsResponse) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *WalletsResponse) GetWallets() []*WalletResponse {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type WalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletRequest) Reset() {
	*x = WalletRequest{}
	mi := &file_pb_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletRequest) ProtoMessage() {}

func (x *WalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletRequest.ProtoReflect.Descriptor instead.
func (*WalletRequest) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *WalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type WalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDefault     bool                   `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	WalletName    string                 `protobuf:"bytes,3,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	Addresses     map[string]string      `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Balance       float32                `protobuf:"fixed32,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_pb_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_pb_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *WalletResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WalletResponse) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *WalletResponse) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *WalletResponse) GetAddresses() map[string]string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *WalletResponse) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *WalletResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pb_wallet_proto protoreflect.FileDescriptor

const file_pb_wallet_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/wallet.proto\x12\x02ws\x1a\x1fgoogle/protobuf/timestamp.proto\"\x10\n" +
	"\x0eWalletsRequest\"\\\n" +
	"\x0fWalletsResponse\x12\x1b\n" +
	"\tis_locked\x18\x01 \x01(\bR\bisLocked\x12,\n" +
	"\awallets\x18\x02 \x03(\v2\x12.ws.WalletResponseR\awallets\",\n" +
	"\rWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"\xb4\x02\n" +
	"\x0eWalletResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"is_default\x18\x02 \x01(\bR\tisDefault\x12\x1f\n" +
	"\vwallet_name\x18\x03 \x01(\tR\n" +
	"walletName\x12?\n" +
	"\taddresses\x18\x04 \x03(\v2!.ws.WalletResponse.AddressesEntryR\taddresses\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x02R\abalance\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a<\n" +
	"\x0eAddressesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012F\n" +
	"\rWalletService\x125\n" +
	"\n" +
	"GetWallets\x12\x12.ws.WalletsRequest\x1a\x13.ws.WalletsResponseB/Z-github.com/filament-labs/filament/internal/pbb\x06proto3"

var (
	file_pb_wallet_proto_rawDescOnce sync.Once
	file_pb_wallet_proto_rawDescData []byte
)

func file_pb_wallet_proto_rawDescGZIP() []byte {
	file_pb_wallet_proto_rawDescOnce.Do(func() {
		file_pb_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_wallet_proto_rawDesc), len(file_pb_wallet_proto_rawDesc)))
	})
	return file_pb_wallet_proto_rawDescData
}

var file_pb_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_wallet_proto_goTypes = []any{
	(*WalletsRequest)(nil),        // 0: ws.WalletsRequest
	(*WalletsResponse)(nil),       // 1: ws.WalletsResponse
	(*WalletRequest)(nil),         // 2: ws.WalletRequest
	(*WalletResponse)(nil),        // 3: ws.WalletResponse
	nil,                           // 4: ws.WalletResponse.AddressesEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_pb_wallet_proto_depIdxs = []int32{
	3, // 0: ws.WalletsResponse.wallets:type_name -> ws.WalletResponse
	4, // 1: ws.WalletResponse.addresses:type_name -> ws.WalletResponse.AddressesEntry
	5, // 2: ws.WalletResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: ws.WalletService.GetWallets:input_type -> ws.WalletsRequest
	1, // 4: ws.WalletService.GetWallets:output_type -> ws.WalletsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_wallet_proto_init() }
func file_pb_wallet_proto_init() {
	if File_pb_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_wallet_proto_rawDesc), len(file_pb_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_wallet_proto_goTypes,
		DependencyIndexes: file_pb_wallet_proto_depIdxs,
		MessageInfos:      file_pb_wallet_proto_msgTypes,
	}.Build()
	File_pb_wallet_proto = out.File
	file_pb_wallet_proto_goTypes = nil
	file_pb_wallet_proto_depIdxs = nil
}
