// Code generated by ent, DO NOT EDIT.

package wallet

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codemaestro64/filament/apps/api/internal/database/orm/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldID, id))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldIsDefault, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldActorID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldName, v))
}

// EncryptedSeed applies equality check predicate on the "encrypted_seed" field. It's identical to EncryptedSeedEQ.
func EncryptedSeed(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldEncryptedSeed, v))
}

// EncryptedKeyJSON applies equality check predicate on the "encrypted_key_json" field. It's identical to EncryptedKeyJSONEQ.
func EncryptedKeyJSON(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldEncryptedKeyJSON, v))
}

// Salt applies equality check predicate on the "salt" field. It's identical to SaltEQ.
func Salt(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldSalt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldIsDefault, v))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldActorID, v))
}

// ActorIDContains applies the Contains predicate on the "actor_id" field.
func ActorIDContains(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContains(FieldActorID, v))
}

// ActorIDHasPrefix applies the HasPrefix predicate on the "actor_id" field.
func ActorIDHasPrefix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasPrefix(FieldActorID, v))
}

// ActorIDHasSuffix applies the HasSuffix predicate on the "actor_id" field.
func ActorIDHasSuffix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasSuffix(FieldActorID, v))
}

// ActorIDEqualFold applies the EqualFold predicate on the "actor_id" field.
func ActorIDEqualFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEqualFold(FieldActorID, v))
}

// ActorIDContainsFold applies the ContainsFold predicate on the "actor_id" field.
func ActorIDContainsFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContainsFold(FieldActorID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Wallet {
	return predicate.Wallet(sql.FieldContainsFold(FieldName, v))
}

// EncryptedSeedEQ applies the EQ predicate on the "encrypted_seed" field.
func EncryptedSeedEQ(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldEncryptedSeed, v))
}

// EncryptedSeedNEQ applies the NEQ predicate on the "encrypted_seed" field.
func EncryptedSeedNEQ(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldEncryptedSeed, v))
}

// EncryptedSeedIn applies the In predicate on the "encrypted_seed" field.
func EncryptedSeedIn(vs ...[]byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldEncryptedSeed, vs...))
}

// EncryptedSeedNotIn applies the NotIn predicate on the "encrypted_seed" field.
func EncryptedSeedNotIn(vs ...[]byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldEncryptedSeed, vs...))
}

// EncryptedSeedGT applies the GT predicate on the "encrypted_seed" field.
func EncryptedSeedGT(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldEncryptedSeed, v))
}

// EncryptedSeedGTE applies the GTE predicate on the "encrypted_seed" field.
func EncryptedSeedGTE(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldEncryptedSeed, v))
}

// EncryptedSeedLT applies the LT predicate on the "encrypted_seed" field.
func EncryptedSeedLT(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldEncryptedSeed, v))
}

// EncryptedSeedLTE applies the LTE predicate on the "encrypted_seed" field.
func EncryptedSeedLTE(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldEncryptedSeed, v))
}

// EncryptedKeyJSONEQ applies the EQ predicate on the "encrypted_key_json" field.
func EncryptedKeyJSONEQ(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldEncryptedKeyJSON, v))
}

// EncryptedKeyJSONNEQ applies the NEQ predicate on the "encrypted_key_json" field.
func EncryptedKeyJSONNEQ(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldEncryptedKeyJSON, v))
}

// EncryptedKeyJSONIn applies the In predicate on the "encrypted_key_json" field.
func EncryptedKeyJSONIn(vs ...[]byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldEncryptedKeyJSON, vs...))
}

// EncryptedKeyJSONNotIn applies the NotIn predicate on the "encrypted_key_json" field.
func EncryptedKeyJSONNotIn(vs ...[]byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldEncryptedKeyJSON, vs...))
}

// EncryptedKeyJSONGT applies the GT predicate on the "encrypted_key_json" field.
func EncryptedKeyJSONGT(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldEncryptedKeyJSON, v))
}

// EncryptedKeyJSONGTE applies the GTE predicate on the "encrypted_key_json" field.
func EncryptedKeyJSONGTE(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldEncryptedKeyJSON, v))
}

// EncryptedKeyJSONLT applies the LT predicate on the "encrypted_key_json" field.
func EncryptedKeyJSONLT(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldEncryptedKeyJSON, v))
}

// EncryptedKeyJSONLTE applies the LTE predicate on the "encrypted_key_json" field.
func EncryptedKeyJSONLTE(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldEncryptedKeyJSON, v))
}

// SaltEQ applies the EQ predicate on the "salt" field.
func SaltEQ(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldSalt, v))
}

// SaltNEQ applies the NEQ predicate on the "salt" field.
func SaltNEQ(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldSalt, v))
}

// SaltIn applies the In predicate on the "salt" field.
func SaltIn(vs ...[]byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldSalt, vs...))
}

// SaltNotIn applies the NotIn predicate on the "salt" field.
func SaltNotIn(vs ...[]byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldSalt, vs...))
}

// SaltGT applies the GT predicate on the "salt" field.
func SaltGT(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldSalt, v))
}

// SaltGTE applies the GTE predicate on the "salt" field.
func SaltGTE(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldSalt, v))
}

// SaltLT applies the LT predicate on the "salt" field.
func SaltLT(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldSalt, v))
}

// SaltLTE applies the LTE predicate on the "salt" field.
func SaltLTE(v []byte) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldSalt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Wallet {
	return predicate.Wallet(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAddresses applies the HasEdge predicate on the "addresses" edge.
func HasAddresses() predicate.Wallet {
	return predicate.Wallet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AddressesTable, AddressesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAddressesWith applies the HasEdge predicate on the "addresses" edge with a given conditions (other predicates).
func HasAddressesWith(preds ...predicate.Address) predicate.Wallet {
	return predicate.Wallet(func(s *sql.Selector) {
		step := newAddressesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Wallet) predicate.Wallet {
	return predicate.Wallet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Wallet) predicate.Wallet {
	return predicate.Wallet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Wallet) predicate.Wallet {
	return predicate.Wallet(sql.NotPredicates(p))
}
