// Code generated by ent, DO NOT EDIT.

package orm

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codemaestro64/filament/apps/api/internal/database/orm/address"
	"github.com/codemaestro64/filament/apps/api/internal/database/orm/wallet"
	pbv1 "github.com/codemaestro64/filament/libs/proto/gen/go/v1"
)

// AddressCreate is the builder for creating a Address entity.
type AddressCreate struct {
	config
	mutation *AddressMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *AddressCreate) SetType(v pbv1.AddressType) *AddressCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *AddressCreate) SetAddress(v string) *AddressCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetWalletID sets the "wallet" edge to the Wallet entity by ID.
func (_c *AddressCreate) SetWalletID(id int) *AddressCreate {
	_c.mutation.SetWalletID(id)
	return _c
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (_c *AddressCreate) SetWallet(v *Wallet) *AddressCreate {
	return _c.SetWalletID(v.ID)
}

// Mutation returns the AddressMutation object of the builder.
func (_c *AddressCreate) Mutation() *AddressMutation {
	return _c.mutation
}

// Save creates the Address in the database.
func (_c *AddressCreate) Save(ctx context.Context) (*Address, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AddressCreate) SaveX(ctx context.Context) *Address {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddressCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddressCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AddressCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`orm: missing required field "Address.type"`)}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`orm: missing required field "Address.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := address.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`orm: validator failed for field "Address.address": %w`, err)}
		}
	}
	if len(_c.mutation.WalletIDs()) == 0 {
		return &ValidationError{Name: "wallet", err: errors.New(`orm: missing required edge "Address.wallet"`)}
	}
	return nil
}

func (_c *AddressCreate) sqlSave(ctx context.Context) (*Address, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AddressCreate) createSpec() (*Address, *sqlgraph.CreateSpec) {
	var (
		_node = &Address{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(address.Table, sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(address.FieldType, field.TypeInt32, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(address.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if nodes := _c.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   address.WalletTable,
			Columns: []string{address.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.wallet_addresses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AddressCreateBulk is the builder for creating many Address entities in bulk.
type AddressCreateBulk struct {
	config
	err      error
	builders []*AddressCreate
}

// Save creates the Address entities in the database.
func (_c *AddressCreateBulk) Save(ctx context.Context) ([]*Address, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Address, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AddressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AddressCreateBulk) SaveX(ctx context.Context) []*Address {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AddressCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AddressCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
