// Code generated by ent, DO NOT EDIT.

package orm

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codemaestro64/filament/apps/api/internal/database/orm/address"
	"github.com/codemaestro64/filament/apps/api/internal/database/orm/wallet"
)

// WalletCreate is the builder for creating a Wallet entity.
type WalletCreate struct {
	config
	mutation *WalletMutation
	hooks    []Hook
}

// SetIsDefault sets the "is_default" field.
func (_c *WalletCreate) SetIsDefault(v bool) *WalletCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *WalletCreate) SetNillableIsDefault(v *bool) *WalletCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetActorID sets the "actor_id" field.
func (_c *WalletCreate) SetActorID(v string) *WalletCreate {
	_c.mutation.SetActorID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *WalletCreate) SetName(v string) *WalletCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEncryptedSeed sets the "encrypted_seed" field.
func (_c *WalletCreate) SetEncryptedSeed(v []byte) *WalletCreate {
	_c.mutation.SetEncryptedSeed(v)
	return _c
}

// SetEncryptedKeyJSON sets the "encrypted_key_json" field.
func (_c *WalletCreate) SetEncryptedKeyJSON(v []byte) *WalletCreate {
	_c.mutation.SetEncryptedKeyJSON(v)
	return _c
}

// SetSalt sets the "salt" field.
func (_c *WalletCreate) SetSalt(v []byte) *WalletCreate {
	_c.mutation.SetSalt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WalletCreate) SetCreatedAt(v time.Time) *WalletCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WalletCreate) SetNillableCreatedAt(v *time.Time) *WalletCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WalletCreate) SetUpdatedAt(v time.Time) *WalletCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// AddAddressIDs adds the "addresses" edge to the Address entity by IDs.
func (_c *WalletCreate) AddAddressIDs(ids ...int) *WalletCreate {
	_c.mutation.AddAddressIDs(ids...)
	return _c
}

// AddAddresses adds the "addresses" edges to the Address entity.
func (_c *WalletCreate) AddAddresses(v ...*Address) *WalletCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAddressIDs(ids...)
}

// Mutation returns the WalletMutation object of the builder.
func (_c *WalletCreate) Mutation() *WalletMutation {
	return _c.mutation
}

// Save creates the Wallet in the database.
func (_c *WalletCreate) Save(ctx context.Context) (*Wallet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WalletCreate) SaveX(ctx context.Context) *Wallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WalletCreate) defaults() {
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := wallet.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wallet.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WalletCreate) check() error {
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`orm: missing required field "Wallet.is_default"`)}
	}
	if _, ok := _c.mutation.ActorID(); !ok {
		return &ValidationError{Name: "actor_id", err: errors.New(`orm: missing required field "Wallet.actor_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`orm: missing required field "Wallet.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := wallet.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`orm: validator failed for field "Wallet.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedSeed(); !ok {
		return &ValidationError{Name: "encrypted_seed", err: errors.New(`orm: missing required field "Wallet.encrypted_seed"`)}
	}
	if v, ok := _c.mutation.EncryptedSeed(); ok {
		if err := wallet.EncryptedSeedValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_seed", err: fmt.Errorf(`orm: validator failed for field "Wallet.encrypted_seed": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EncryptedKeyJSON(); !ok {
		return &ValidationError{Name: "encrypted_key_json", err: errors.New(`orm: missing required field "Wallet.encrypted_key_json"`)}
	}
	if v, ok := _c.mutation.EncryptedKeyJSON(); ok {
		if err := wallet.EncryptedKeyJSONValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_key_json", err: fmt.Errorf(`orm: validator failed for field "Wallet.encrypted_key_json": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Salt(); !ok {
		return &ValidationError{Name: "salt", err: errors.New(`orm: missing required field "Wallet.salt"`)}
	}
	if v, ok := _c.mutation.Salt(); ok {
		if err := wallet.SaltValidator(v); err != nil {
			return &ValidationError{Name: "salt", err: fmt.Errorf(`orm: validator failed for field "Wallet.salt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`orm: missing required field "Wallet.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`orm: missing required field "Wallet.updated_at"`)}
	}
	return nil
}

func (_c *WalletCreate) sqlSave(ctx context.Context) (*Wallet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WalletCreate) createSpec() (*Wallet, *sqlgraph.CreateSpec) {
	var (
		_node = &Wallet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wallet.Table, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(wallet.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.ActorID(); ok {
		_spec.SetField(wallet.FieldActorID, field.TypeString, value)
		_node.ActorID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(wallet.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.EncryptedSeed(); ok {
		_spec.SetField(wallet.FieldEncryptedSeed, field.TypeBytes, value)
		_node.EncryptedSeed = value
	}
	if value, ok := _c.mutation.EncryptedKeyJSON(); ok {
		_spec.SetField(wallet.FieldEncryptedKeyJSON, field.TypeBytes, value)
		_node.EncryptedKeyJSON = value
	}
	if value, ok := _c.mutation.Salt(); ok {
		_spec.SetField(wallet.FieldSalt, field.TypeBytes, value)
		_node.Salt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wallet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if nodes := _c.mutation.AddressesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.AddressesTable,
			Columns: []string{wallet.AddressesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(address.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WalletCreateBulk is the builder for creating many Wallet entities in bulk.
type WalletCreateBulk struct {
	config
	err      error
	builders []*WalletCreate
}

// Save creates the Wallet entities in the database.
func (_c *WalletCreateBulk) Save(ctx context.Context) ([]*Wallet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Wallet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WalletMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WalletCreateBulk) SaveX(ctx context.Context) []*Wallet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WalletCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WalletCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
