// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file pb/message.proto (package ws, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file pb/message.proto.
 */
export const file_pb_message: GenFile = /*@__PURE__*/
  fileDesc("ChBwYi9tZXNzYWdlLnByb3RvEgJ3cyImCgdNZXNzYWdlEg0KBWV2ZW50GAEgASgJEgwKBGRhdGEYAiABKAxCL1otZ2l0aHViLmNvbS9maWxhbWVudC1sYWJzL2ZpbGFtZW50L2ludGVybmFsL3BiYgZwcm90bzM");

/**
 * @generated from message ws.Message
 */
export type Message = Message$1<"ws.Message"> & {
  /**
   * @generated from field: string event = 1;
   */
  event: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message ws.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_pb_message, 0);

