// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file pb/ping.proto (package ws, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file pb/ping.proto.
 */
export const file_pb_ping: GenFile = /*@__PURE__*/
  fileDesc("Cg1wYi9waW5nLnByb3RvEgJ3cyINCgtQaW5nUmVxdWVzdCIhCgxQaW5nUmVzcG9uc2USEQoJdGltZXN0YW1wGAEgASgDMjgKC1BpbmdTZXJ2aWNlEikKBFBpbmcSDy53cy5QaW5nUmVxdWVzdBoQLndzLlBpbmdSZXNwb25zZUIvWi1naXRodWIuY29tL2ZpbGFtZW50LWxhYnMvZmlsYW1lbnQvaW50ZXJuYWwvcGJiBnByb3RvMw");

/**
 * @generated from message ws.PingRequest
 */
export type PingRequest = Message<"ws.PingRequest"> & {
};

/**
 * Describes the message ws.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_pb_ping, 0);

/**
 * @generated from message ws.PingResponse
 */
export type PingResponse = Message<"ws.PingResponse"> & {
  /**
   * @generated from field: int64 timestamp = 1;
   */
  timestamp: bigint;
};

/**
 * Describes the message ws.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_pb_ping, 1);

/**
 * @generated from service ws.PingService
 */
export const PingService: GenService<{
  /**
   * @generated from rpc ws.PingService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_pb_ping, 0);

