// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file pb/ping.proto (package ws, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PingRequest, PingResponse } from "./ping_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ws.PingService
 */
export const PingService = {
  typeName: "ws.PingService",
  methods: {
    /**
     * @generated from rpc ws.PingService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

