// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file pb/wallet.proto (package ws, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { WalletsRequest, WalletsResponse } from "./wallet_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ws.WalletService
 */
export const WalletService = {
  typeName: "ws.WalletService",
  methods: {
    /**
     * @generated from rpc ws.WalletService.GetWallets
     */
    getWallets: {
      name: "GetWallets",
      I: WalletsRequest,
      O: WalletsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

