// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file pb/wallet.proto (package ws, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file pb/wallet.proto.
 */
export const file_pb_wallet: GenFile = /*@__PURE__*/
  fileDesc("Cg9wYi93YWxsZXQucHJvdG8SAndzIhAKDldhbGxldHNSZXF1ZXN0IkkKD1dhbGxldHNSZXNwb25zZRIRCglpc19sb2NrZWQYASABKAgSIwoHd2FsbGV0cxgCIAMoCzISLndzLldhbGxldFJlc3BvbnNlIiIKDVdhbGxldFJlcXVlc3QSEQoJd2FsbGV0X2lkGAEgASgJIu4BCg5XYWxsZXRSZXNwb25zZRIKCgJpZBgBIAEoCRISCgppc19kZWZhdWx0GAIgASgIEhMKC3dhbGxldF9uYW1lGAMgASgJEjQKCWFkZHJlc3NlcxgEIAMoCzIhLndzLldhbGxldFJlc3BvbnNlLkFkZHJlc3Nlc0VudHJ5Eg8KB2JhbGFuY2UYBSABKAISLgoKY3JlYXRlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAaMAoOQWRkcmVzc2VzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ATJGCg1XYWxsZXRTZXJ2aWNlEjUKCkdldFdhbGxldHMSEi53cy5XYWxsZXRzUmVxdWVzdBoTLndzLldhbGxldHNSZXNwb25zZUIvWi1naXRodWIuY29tL2ZpbGFtZW50LWxhYnMvZmlsYW1lbnQvaW50ZXJuYWwvcGJiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message ws.WalletsRequest
 */
export type WalletsRequest = Message<"ws.WalletsRequest"> & {
};

/**
 * Describes the message ws.WalletsRequest.
 * Use `create(WalletsRequestSchema)` to create a new message.
 */
export const WalletsRequestSchema: GenMessage<WalletsRequest> = /*@__PURE__*/
  messageDesc(file_pb_wallet, 0);

/**
 * @generated from message ws.WalletsResponse
 */
export type WalletsResponse = Message<"ws.WalletsResponse"> & {
  /**
   * @generated from field: bool is_locked = 1;
   */
  isLocked: boolean;

  /**
   * @generated from field: repeated ws.WalletResponse wallets = 2;
   */
  wallets: WalletResponse[];
};

/**
 * Describes the message ws.WalletsResponse.
 * Use `create(WalletsResponseSchema)` to create a new message.
 */
export const WalletsResponseSchema: GenMessage<WalletsResponse> = /*@__PURE__*/
  messageDesc(file_pb_wallet, 1);

/**
 * @generated from message ws.WalletRequest
 */
export type WalletRequest = Message<"ws.WalletRequest"> & {
  /**
   * @generated from field: string wallet_id = 1;
   */
  walletId: string;
};

/**
 * Describes the message ws.WalletRequest.
 * Use `create(WalletRequestSchema)` to create a new message.
 */
export const WalletRequestSchema: GenMessage<WalletRequest> = /*@__PURE__*/
  messageDesc(file_pb_wallet, 2);

/**
 * @generated from message ws.WalletResponse
 */
export type WalletResponse = Message<"ws.WalletResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: bool is_default = 2;
   */
  isDefault: boolean;

  /**
   * @generated from field: string wallet_name = 3;
   */
  walletName: string;

  /**
   * @generated from field: map<string, string> addresses = 4;
   */
  addresses: { [key: string]: string };

  /**
   * @generated from field: float balance = 5;
   */
  balance: number;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message ws.WalletResponse.
 * Use `create(WalletResponseSchema)` to create a new message.
 */
export const WalletResponseSchema: GenMessage<WalletResponse> = /*@__PURE__*/
  messageDesc(file_pb_wallet, 3);

/**
 * @generated from service ws.WalletService
 */
export const WalletService: GenService<{
  /**
   * @generated from rpc ws.WalletService.GetWallets
   */
  getWallets: {
    methodKind: "unary";
    input: typeof WalletsRequestSchema;
    output: typeof WalletsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_pb_wallet, 0);

