// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pb/wallet.proto

package pbconnect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	pb "github.com/filament-labs/filament/internal/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// WalletServiceName is the fully-qualified name of the WalletService service.
	WalletServiceName = "ws.WalletService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WalletServiceGetWalletsProcedure is the fully-qualified name of the WalletService's GetWallets
	// RPC.
	WalletServiceGetWalletsProcedure = "/ws.WalletService/GetWallets"
)

// WalletServiceClient is a client for the ws.WalletService service.
type WalletServiceClient interface {
	GetWallets(context.Context, *connect_go.Request[pb.WalletsRequest]) (*connect_go.Response[pb.WalletsResponse], error)
}

// NewWalletServiceClient constructs a client for the ws.WalletService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWalletServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) WalletServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &walletServiceClient{
		getWallets: connect_go.NewClient[pb.WalletsRequest, pb.WalletsResponse](
			httpClient,
			baseURL+WalletServiceGetWalletsProcedure,
			opts...,
		),
	}
}

// walletServiceClient implements WalletServiceClient.
type walletServiceClient struct {
	getWallets *connect_go.Client[pb.WalletsRequest, pb.WalletsResponse]
}

// GetWallets calls ws.WalletService.GetWallets.
func (c *walletServiceClient) GetWallets(ctx context.Context, req *connect_go.Request[pb.WalletsRequest]) (*connect_go.Response[pb.WalletsResponse], error) {
	return c.getWallets.CallUnary(ctx, req)
}

// WalletServiceHandler is an implementation of the ws.WalletService service.
type WalletServiceHandler interface {
	GetWallets(context.Context, *connect_go.Request[pb.WalletsRequest]) (*connect_go.Response[pb.WalletsResponse], error)
}

// NewWalletServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWalletServiceHandler(svc WalletServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	walletServiceGetWalletsHandler := connect_go.NewUnaryHandler(
		WalletServiceGetWalletsProcedure,
		svc.GetWallets,
		opts...,
	)
	return "/ws.WalletService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WalletServiceGetWalletsProcedure:
			walletServiceGetWalletsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWalletServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWalletServiceHandler struct{}

func (UnimplementedWalletServiceHandler) GetWallets(context.Context, *connect_go.Request[pb.WalletsRequest]) (*connect_go.Response[pb.WalletsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("ws.WalletService.GetWallets is not implemented"))
}
