/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppTitle: typeof import('./components/AppTitle.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splash: typeof import('./components/AppTitle.vueplash.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
  }
}
